// <auto-generated />
using System;
using App.Modules.Core.Infrastructure.Data.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Modules.Core.Infrastructure.Migrations
{
    [DbContext(typeof(ModuleDbContext))]
    [Migration("20190427040419_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Modules.Core.Shared.Models.Entities.DataClassification", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedOnUtc")
                        .IsRequired();

                    b.Property<string>("DeletedByPrincipalId")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("DeletedOnUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(32768);

                    b.Property<int>("DisplayOrderHint");

                    b.Property<string>("DisplayStyleHint")
                        .HasMaxLength(64);

                    b.Property<bool>("Enabled");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .IsRequired();

                    b.Property<int>("RecordState");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedByPrincipalId")
                        .HasName("IX_DataClassification_LastModifiedByPrincipalId");

                    b.HasIndex("LastModifiedOnUtc")
                        .HasName("IX_DataClassification_LastModifiedOnUtc");

                    b.HasIndex("RecordState")
                        .HasName("IX_DataClassification_RecordState");

                    b.HasIndex("Title")
                        .HasName("IX_DataClassification_Title");

                    b.ToTable("DataClassifications","Core");
                });
#pragma warning restore 612, 618
        }
    }
}
