// <auto-generated />
using System;
using App.Modules.KWMODULE.Infrastructure.Data.Db.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Modules.KWMODULE.Infrastructure.Data.Db.Migrations
{
    [DbContext(typeof(ModuleDbContext))]
    partial class ModuleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Modules.KWMODULE.Shared.Models.Entities.Example", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Description");

                    b.Property<int>("RecordState");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("RecordState")
                        .HasName("IX_Example_RecordState");

                    b.ToTable("Examples","KWMODULE");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a027fd1-35f8-da13-8698-39ee48ea1fdf"),
                            Description = "Some Description",
                            RecordState = 0,
                            Title = "Some Title"
                        },
                        new
                        {
                            Id = new Guid("2e4ef525-4673-c5c5-a9ad-39ee48ea1fdf"),
                            RecordState = 0,
                            Title = "Another Title"
                        });
                });

            modelBuilder.Entity("App.Modules.KWMODULE.Shared.Models.Entities.LinkedExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DataClassificationFK");

                    b.Property<string>("Description");

                    b.Property<int>("RecordState");

                    b.Property<byte[]>("Timestamp");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("LinkedExamples","KWMODULE");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d4426fd-9539-38b1-150f-39ee48ea1fe0"),
                            DataClassificationFK = 1,
                            Description = "Some Description",
                            RecordState = 0,
                            Title = "Some Title"
                        },
                        new
                        {
                            Id = new Guid("0084e833-09c5-5198-a877-39ee48ea1fe0"),
                            DataClassificationFK = 6,
                            RecordState = 0,
                            Title = "Another Title"
                        });
                });

            modelBuilder.Entity("App.Modules.KWMODULE.Shared.Models.Entities.TenantedExample", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Description");

                    b.Property<int>("RecordState");

                    b.Property<Guid>("TenantFK");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RecordState")
                        .HasName("IX_TenantedExample_RecordState");

                    b.ToTable("TenantedExamples","KWMODULE");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bdb7f45-9a0c-203a-e3d9-39ee48ea1fe0"),
                            Description = "Some Description",
                            RecordState = 0,
                            TenantFK = new Guid("00000003-0000-0000-0000-000000000000"),
                            Title = "Some Title"
                        },
                        new
                        {
                            Id = new Guid("640d5b99-ab4c-843b-d162-39ee48ea1fe1"),
                            RecordState = 0,
                            TenantFK = new Guid("00000003-0000-0000-0000-000000000000"),
                            Title = "Another Title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
