// <auto-generated />
using System;
using App.Modules.Core.Infrastructure.Data.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Modules.Core.Infrastructure.Migrations
{
    [DbContext(typeof(CoreModuleDbContext))]
    [Migration("20190427051055_Notification")]
    partial class Notification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Modules.Core.Shared.Models.Entities.DataClassification", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedOnUtc")
                        .IsRequired();

                    b.Property<string>("DeletedByPrincipalId")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("DeletedOnUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(32768);

                    b.Property<int>("DisplayOrderHint");

                    b.Property<string>("DisplayStyleHint")
                        .HasMaxLength(64);

                    b.Property<bool>("Enabled");

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .IsRequired();

                    b.Property<int>("RecordState");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedByPrincipalId")
                        .HasName("IX_DataClassification_LastModifiedByPrincipalId");

                    b.HasIndex("LastModifiedOnUtc")
                        .HasName("IX_DataClassification_LastModifiedOnUtc");

                    b.HasIndex("RecordState")
                        .HasName("IX_DataClassification_RecordState");

                    b.HasIndex("Title")
                        .HasName("IX_DataClassification_Title");

                    b.ToTable("DataClassifications","Core");
                });

            modelBuilder.Entity("App.Modules.Core.Shared.Models.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedOnUtc")
                        .IsRequired();

                    b.Property<int?>("DataClassificationFK");

                    b.Property<string>("DeletedByPrincipalId")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("DeletedOnUtc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<bool>("Enabled");

                    b.Property<string>("HostName")
                        .HasMaxLength(64);

                    b.Property<bool?>("IsDefault");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .IsRequired();

                    b.Property<int>("RecordState");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("DataClassificationFK");

                    b.HasIndex("DisplayName")
                        .HasName("IX_Tenant_DisplayName");

                    b.HasIndex("Key")
                        .HasName("IX_Tenant_Key");

                    b.HasIndex("LastModifiedByPrincipalId")
                        .HasName("IX_Tenant_LastModifiedByPrincipalId");

                    b.HasIndex("LastModifiedOnUtc")
                        .HasName("IX_Tenant_LastModifiedOnUtc");

                    b.HasIndex("RecordState")
                        .HasName("IX_Tenant_RecordState");

                    b.ToTable("Tenants","Core");
                });

            modelBuilder.Entity("App.Modules.Core.Shared.Models.Entities.TenantClaim", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("AuthoritySignature")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedOnUtc")
                        .IsRequired();

                    b.Property<string>("DeletedByPrincipalId")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("DeletedOnUtc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .IsRequired();

                    b.Property<int>("RecordState");

                    b.Property<Guid>("TenantFK");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Value")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.HasIndex("Authority")
                        .HasName("IX_TenantClaim_Authority");

                    b.HasIndex("Key")
                        .HasName("IX_TenantClaim_Key");

                    b.HasIndex("LastModifiedByPrincipalId")
                        .HasName("IX_TenantClaim_LastModifiedByPrincipalId");

                    b.HasIndex("LastModifiedOnUtc")
                        .HasName("IX_TenantClaim_LastModifiedOnUtc");

                    b.HasIndex("RecordState")
                        .HasName("IX_TenantClaim_RecordState");

                    b.HasIndex("TenantFK");

                    b.ToTable("TenantClaims","Core");
                });

            modelBuilder.Entity("App.Modules.Core.Shared.Models.Entities.TenantProperty", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedOnUtc")
                        .IsRequired();

                    b.Property<string>("DeletedByPrincipalId")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("DeletedOnUtc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("LastModifiedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("LastModifiedOnUtc")
                        .IsRequired();

                    b.Property<int>("RecordState");

                    b.Property<Guid>("TenantFK");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Value")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .HasName("IX_TenantProperty_Key");

                    b.HasIndex("LastModifiedByPrincipalId")
                        .HasName("IX_TenantProperty_LastModifiedByPrincipalId");

                    b.HasIndex("LastModifiedOnUtc")
                        .HasName("IX_TenantProperty_LastModifiedOnUtc");

                    b.HasIndex("RecordState")
                        .HasName("IX_TenantProperty_RecordState");

                    b.HasIndex("TenantFK");

                    b.ToTable("TenantProperties","Core");
                });

            modelBuilder.Entity("App.Modules.Core.Shared.Models.Entities.Tenant", b =>
                {
                    b.HasOne("App.Modules.Core.Shared.Models.Entities.DataClassification", "DataClassification")
                        .WithMany()
                        .HasForeignKey("DataClassificationFK");
                });

            modelBuilder.Entity("App.Modules.Core.Shared.Models.Entities.TenantClaim", b =>
                {
                    b.HasOne("App.Modules.Core.Shared.Models.Entities.Tenant")
                        .WithMany("Claims")
                        .HasForeignKey("TenantFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("App.Modules.Core.Shared.Models.Entities.TenantProperty", b =>
                {
                    b.HasOne("App.Modules.Core.Shared.Models.Entities.Tenant")
                        .WithMany("Properties")
                        .HasForeignKey("TenantFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
